# Generated by Django 3.1.3 on 2020-11-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_views',
            fields=[
                ('page_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('page_views', models.IntegerField(default=0)),
            ],
        ),
    ]
